name: biquge.biz
host: https://www.biquge.biz
encoding: GBK
headers:
  user-agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36
category:
  玄幻: 1
hasChapter: true
concurrent: 3
shortContent: 500
newChapterListUrl: https://www.biquge.biz